version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "john-websocket-example"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1kabayuw3nuhn"
s3_prefix = "john-websocket-example"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "TableName=\"simplechat_connections\""
image_repositories = []
